package com.siue.nursingHome;

import java.util.Map;
import java.util.TreeMap;

public class Constants {
    public static final Map<String, String> STATE_LIST = new TreeMap<String, String>() {{
        put("Alabama", "AL");
        put("Alaska", "AK");
        put("Alberta", "AB");
        put("American Samoa", "AS");
        put("Arizona", "AZ");
        put("Arkansas", "AR");
        put("Armed Forces (AE)", "AE");
        put("Armed Forces Americas", "AA");
        put("Armed Forces Pacific", "AP");
        put("British Columbia", "BC");
        put("California", "CA");
        put("Colorado", "CO");
        put("Connecticut", "CT");
        put("Delaware", "DE");
        put("District Of Columbia", "DC");
        put("Florida", "FL");
        put("Georgia", "GA");
        put("Guam", "GU");
        put("Hawaii", "HI");
        put("Idaho", "ID");
        put("Illinois", "IL");
        put("Indiana", "IN");
        put("Iowa", "IA");
        put("Kansas", "KS");
        put("Kentucky", "KY");
        put("Louisiana", "LA");
        put("Maine", "ME");
        put("Manitoba", "MB");
        put("Maryland", "MD");
        put("Massachusetts", "MA");
        put("Michigan", "MI");
        put("Minnesota", "MN");
        put("Mississippi", "MS");
        put("Missouri", "MO");
        put("Montana", "MT");
        put("Nebraska", "NE");
        put("Nevada", "NV");
        put("New Brunswick", "NB");
        put("New Hampshire", "NH");
        put("New Jersey", "NJ");
        put("New Mexico", "NM");
        put("New York", "NY");
        put("Newfoundland", "NF");
        put("North Carolina", "NC");
        put("North Dakota", "ND");
        put("Northwest Territories", "NT");
        put("Nova Scotia","NS");
        put("Nunavut","NU");
        put("Ohio","OH");
        put("Oklahoma","OK");
        put("Ontario","ON");
        put("Oregon","OR");
        put("Pennsylvania","PA");
        put("Prince Edward Island","PE");
        put("Puerto Rico","PR");
        put("Quebec","QC");
        put("Rhode Island","RI");
        put("Saskatchewan","SK");
        put("South Carolina","SC");
        put("South Dakota","SD");
        put("Tennessee","TN");
        put("Texas","TX");
        put("Utah","UT");
        put("Vermont","VT");
        put("Virgin Islands","VI");
        put("Virginia","VA");
        put("Washington","WA");
        put("West Virginia","WV");
        put("Wisconsin","WI");
        put("Wyoming","WY");
        put("Yukon Territory","YT");
    }};
}

